services:
  pylon_to_mqtt:
    container_name: pylon_to_mqtt
    image: classicdiy/pylon_to_mqtt:latest
    restart: unless-stopped
    devices: 
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto
    environment:
      - LOGLEVEL=INFO
      - PYLON_PORT=/dev/ttyUSB0
      - RACK_NAME=Main
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_ROOT=PylonToMQTT
 #     - MQTT_USER=ClassicPublisher
 #     - MQTT_PASS=ClassicPub123
 #    - SOK=true


