version: "3"
services:
  pylon_to_mqtt:
    container_name: pylon_to_mqtt
    image: pylon_to_mqtt
    restart: unless-stopped
    build: .
    network_mode: host
    volumes:
      - /dev/bms_lv:/dev/bms_lv
    privileged: true
    environment:
      - LOGLEVEL=DEBUG
      - PYLON_PORT=/dev/bms_lv
      - RACK_NAME=Main
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_ROOT=PylonToMQTT
      - MQTT_USER=
      - MQTT_PASS=
      - PUBLISH_RATE=5
